### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by Axkaban** [Slushnas/vidbits-capstone#1]
Really good work, one thing I might mention is that building the video object and the validateSync is always set the same,
[https://github.com/Slushnas/vidbits-capstone/blob/master/routes/videos.js#L37-L40](https://github.com/Slushnas/vidbits-capstone/blob/master/routes/videos.js#L37-L40)
so you could create two middleware functions to search and one to build :
```
const findVideo = async (request) => {
  const {id} = request.params;

  return await Video.findOne({ _id: id });
}

const buildVideo = (video, {title, description, url}) => {
  video.title = title;
  video.description = description;
  video.url = url;

  video.validateSync();
};
```
that way you can just call it and pass parameters.

**Comment by Slushnas** [comment]
I created a new function to build and validate the model as suggested.
