### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by Axkaban** [Slushnas/vidbits-capstone#2]
Routes

Create, delete, visit, and update are very well written, Well done!

Nice work with the error catching [https://github.com/Slushnas/vidbits-capstone/blob/master/test/routes/create-test.js#L78-L108](https://github.com/Slushnas/vidbits-capstone/blob/master/test/routes/create-test.js#L78-L108)

Really good job on your feature test!

[https://github.com/Slushnas/vidbits-capstone/blob/master/test/features/user-updating-video-test.js#L18-L28](https://github.com/Slushnas/vidbits-capstone/blob/master/test/features/user-updating-video-test.js#L18-L28)

**Comment by Slushnas** [comment]
Thanks!
